extends Node

onready var g = get_parent()

func _ready():
	# write(passage, b_image, b_image_color, b_color)
	
	### PROLOGUE ###
	g.write("The breeze shook the pine boughs overhead as the young Mrs. Mary Baily, known to friends as \"Ashley\", wandered up the trail. With each step, her lungs took in the healing air. Far from the miasma of Newark, she hoped that the sweet forest's scent would allow her body the rest it needed before she could return to her everyday life.\n\nHer darling husband, Bernard, was a few steps ahead of her. He pushed shrub branches to the side to allow Ashley passage through the trail. It was his duty to protect her from troubles along the way, whether they be stray creatures or sharp thorns. The war had given him enough of a chance to fight, but saving his wife would be a different type of battle.","res://images/Berkeley_Heights_NJ_woods_trans.png")
	g.write("At last, they arrived at a small clearing. Ashley lifted her walking-skirts so as to avoid the dust and brambles before sitting on a log. The sun's rays passed between the trees, catching the light of her alabaster skin. Bernard took a place beside her.\n\n\"How is the forest treating you?\" Bernard asked, entwining his fingers with her slim fingers.\n\nAshley smiled, a slight glow upon her cheeks. \"It's treating me well, although my legs do tire after such a journey. Legs as strong as yours would never do so.\"","res://images/Berkeley_Heights_NJ_woods_trans.png")
	g.write("Bernard laughed, and his gruff voice echoed through the clearing. \"But they do, for they carry the weight of a sore heart.\"\n\n\"Ah, the greatest weight of all.\" Ashley remarked solemnly, though she would have liked to respond, \"Is my health making your heart as sore as this corset is making my chest?\"\n\nThe few minutes of reprieve were all Ashley needed before they continued along their route. Ashley's speed increased. There was plenty to do at home.\n\nAs they reached the edge of the forest, a shadow moved and startled a flock of birds. Bernard instinctively reached for the shiny, silver musket on his hip. His eyes darted as he searched for the source of the disturbance. Finding nothing, he relaxed his grip on the gun.")
	g.write("\"What was that, Bernard?\" Ashley's voice was pained with concern.\n\nBernard smiled. \"Just a fox or a bear, I would suppose.\"\n\nAs he spoke, Ashley spotted two of the birds flying in a circular pattern above them. Their long necks and thin wings seemed harsh against the bright blue of the sky. One of them screeched as they flew downwards. As they neared, the bird's features became increasingly strange. Their mouths were not beaked, but round, not unlike a horse's muzzle. Their wings were leathery, as a bat's would be. Their arms twisted downwards like monstrous pitch forks, their thin tails twisted in the wind, and heavy hooves were attached to their spindly legs.")
	g.write("One of the bird opened its mouth and let out a bone-chilling screech. Bernard gripped his gun, watching the terrible creatures. Beads of sweat formed on his brow.\n\nSuddenly, one of the monsters dove, and its arm grasped Ashley's hair. It flapped with a fervor, dragging her away. The other monster flew straight towards Bernard's face. He fired.\n\nThe monster did not react.\n\nAshley yelped as she ripped herself from the other monster's claws. Long tendrils hair tumbled to the ground. She sprinted towards her husband. The monster flew past her, slashing her shoulder.")
	g.write("Bernard spun around and shot the monster at Ashleyfs side. At point-blank range, there was no way he could miss. The shot rang out, and the monster fell. Blood splattered on Ashleyfs skirt.\n\nThe second monster landed on the ground. Bernard looked at it, hesitant. There was something subtle in its eyes. He could not place it. He stood, mesmerised.\n\n\"You've no business here\", Bernard whispered.\n\nThe monster fluttered its wings, rising into the air slowly, whimpering. Perhaps it was a twisted mourning ritual. Bernard relaxed. He walked closer to the strange beast.")
	g.write("One of the monster's hooves swung out. It collided with Bernard's neck. Bernard gave way under it.\n\nAshley's lungs stopped taking in air. Her head was spinning. The monster flew towards her, hooves first. She barely registered the weight the gun felt in her hands. The trigger felt miles away. Her finger moved towards her palm. Gunpowder burned her hand as a bullet shot out. The monsterfs left wing split in two. She shot again. A perfect hit.\n\nBut Ashley did not care about that now. Her mind was entirely focused on the man to whom she swore her life. Bernard's limp body laid on the ground. His cheeks were already growing pale. Her knees relaxed. She was still unable to breathe. Her heart was racing.")
	g.write("This was it, she knew. As her eyes lost focus, the last thought in her mind was, \"Bernard, my love, we will be together in heaven\". ")
	g.write("The End of Prologue")
	### CHAPTER 1 ###
	pass
